---

- name: Ensure librewolf is installed
  community.general.pacman:
    name:
      - librewolf-bin
    state: present

- name: Make sure .librewolf dir exisits
  ansible.builtin.file:
    path: /home/{{ user_name }}/.librewolf
    state: directory
    mode: "0700"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Make sure librewolf.overrides.cfg exists
  ansible.builtin.copy:
    src: librewolf.cfg
    dest: /home/{{ user_name }}/.librewolf/librewolf.overrides.cfg
    mode: "0644"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
