operator:
  create: true
  token:
    value: {{ onepassword_connect_token }}
connect:
  credentials_base64: {{ onepassword_connect_credentials }}
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx-internal
      kubernetes.io/tls-acme: 'true'
    ingressClassName: "nginx-internal"
    pathType: Prefix
    hosts:
      - host: {{ onepassword_ingress_url }}
        paths: []
    extraPaths: []
    tls:
      - secretName: onepassword-tls
        hosts:
          - {{ onepassword_ingress_url }}
