apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: dagonite-empire
  namespace: dagonite-empire
spec:
  chart:
    spec:
      chart: dagonite-empire
      version: 0.1.*
      sourceRef:
        kind: HelmRepository
        name: drik-homelab
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: dagonite-empire
  values:
    image:
      repository: docker.io/drikqlis/dagonite-empire # {"$imagepolicy": "flux-system:dagonite-empire:name"}
      tag: 0.2.4 # {"$imagepolicy": "flux-system:dagonite-empire:tag"}
  valuesFrom:
  - kind: ConfigMap
    name: dagonite-empire-values
    valuesKey: values.yaml
  - kind: Secret
    name: dagonite-empire-secret-values
    valuesKey: notesPlain
