---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-values
  namespace: cert-manager
data:
  values.yaml: |-
    crds:
      enabled: true
    replicaCount: 1
    resources: {}
    dns01RecursiveNameservers: 1.1.1.1:53
