---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-values
  namespace: cert-manager
data:
  values.yaml: |-
    crds:
      enabled: true
    replicaCount: 1
    resources: {}
    dns01RecursiveNameservers: "https://1.1.1.1/dns-query,https://8.8.8.8/dns-query"
    dns01RecursiveNameserversOnly: true
    enableCertificateOwnerRef: true
    global:
      logLevel: 6
