---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-values
  namespace: cert-manager
data:
  values.yaml: |-
    crds:
      enabled: true
    replicaCount: 1
    resources: {}
    extraArgs:
      - --enable-certificate-owner-ref=true
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53
    dns01RecursiveNameservers: "1.1.1.1:53,8.8.8.8:53"
    dns01RecursiveNameserversOnly: true
    enableCertificateOwnerRef: true
