---
apiVersion: v1
kind: ConfigMap
metadata:
  name: onepassword-values
  namespace: onepassword
data:
  values.yaml: |-
    operator:
      create: true
    connect:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/ingress.class: nginx-internal
          kubernetes.io/tls-acme: 'true'
        ingressClassName: "nginx-internal"
        pathType: Prefix
        hosts:
          - host: onepassword.drik.it
            paths: []
        extraPaths: []
        tls:
          - secretName: onepassword-tls
            hosts:
              - onepassword.drik.it
