---

crypt_passphrase: "{{ lookup('community.general.bitwarden', 'mk_secrets', field='crypt_passphrase') | join }}"
ssh_pub_keys: "{{ lookup('community.general.bitwarden', 'group_vars_all', field='ssh_pub_key_1') }}"
pacman_local_mirror_url: "{{ lookup('community.general.bitwarden', 'group_vars_all', field='pacman_local_mirror_url') | join }}"

certbot_cloudflare_api_token: "{{ lookup('community.general.bitwarden', 'group_vars_kube_nodes', field='cert_manager_cloudflare_api_token') | first }}"
certbot_email: "{{ lookup('community.general.bitwarden', 'group_vars_kube_nodes', field='cert_manager_email') | first }}"
