---

- name: Ensure kvm software is installed
  community.general.pacman:
    name:
      - libvirt
      - dmidecode
      - qemu
      - iptables-nft
      - edk2-ovmf
      - dnsmasq
      - bridge-utils
      - swtpm
      - libvirt-python
    state: present
    extra_args: --ask 4
  register: kvm_libvirt_installed

- name: Ensure gui kvm software is installed
  community.general.pacman:
    name:
      - virt-manager
      - virt-viewer
    state: present
  when: gui_enabled

- name: Reboot if libvirt installed # noqa no-handler
  ansible.builtin.reboot:
  when: kvm_libvirt_installed.changed

- name: Allow host resolution
  ansible.builtin.lineinfile:
    dest: /etc/nsswitch.conf
    regexp: "^hosts:"
    line: "hosts: mymachines resolve [!UNAVAIL=return] files libvirt libvirt_guest myhostname dns"

- name: Add main user to libvirt group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: libvirt
    append: true

- name: Enable and start libvirt service
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true

- name: Kvm network
  tags: kvm_bridge
  block:
    - name: Remove default network
      community.libvirt.virt_net:
        state: absent
        name: default

    - name: Define bridge network
      community.libvirt.virt_net:
        command: define
        name: host-bridge
        xml: '{{ lookup("template", "host-bridge.xml.j2") }}'

    - name: Activate bridge network
      community.libvirt.virt_net:
        state: active
        name: host-bridge

    - name: Ensure that network autostarts
      community.libvirt.virt_net:
        autostart: true
        name: host-bridge

    - name: Create master bridge
      community.general.nmcli:
        type: bridge
        conn_name: "{{ kvm_bridge_interface }}"
        stp: false
        state: present

    - name: Create slave bridge
      community.general.nmcli:
        type: bridge-slave
        conn_name: bridge-slave-{{ lan_interface }}
        ifname: "{{ lan_interface }}"
        master: "{{ kvm_bridge_interface }}"
        state: present
      notify: Start bridge slave
