server:
  resources: {{ authentik_resources_server }}
  replicas: {{ authentik_server_replicas }}
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - {{ authentik_host }}
    paths:
      - /
    pathType: Prefix
    tls:
      - hosts:
        - {{ authentik_host }}
        secretName: authentik-certs
worker:
  resources: {{ authentik_resources_worker }}
  replicas: {{ authentik_worker_replicas }}

authentik:
  error_reporting:
      enabled: false
  disable_startup_analytics: true
  secret_key: {{ authentik_secret_key }}
  email:
    host: {{ authentik_email_host }}
    port: {{ authentik_email_port }}
    username: {{ authentik_email_username }}
    password: {{ authentik_email_password }}
    use_tls: {{ authentik_email_use_tls }}
    from: {{ authentik_email_from }}
  postgresql:
    password: {{ authentik_postgresql_password }}
  redis:
    password: {{ authentik_redis_password }}

postgresql:
  enabled: true
  auth:
    password: {{ authentik_postgresql_password }}
  clusterDomain: {{ kubernetes_dns_domain }}
  primary:
    resources: {}
  readReplicas:
    resources: {}

redis:
  enabled: true
  auth:
    enabled: true
    password: {{ authentik_redis_password }}
  clusterDomain: {{ kubernetes_dns_domain }}
