---

- name: Post installation configration
  hosts: managed
  become: true
  tasks:

    - name: Basic configuration
      tags: [basic]
      block:
        - name: Network configuration
          ansible.builtin.import_role:
            name: network
          tags: [network]
          when: network_config is defined

        - name: Package upgrade
          ansible.builtin.import_role:
            name: upgrade
          tags: [upgrade]

        - name: Standard configuration
          ansible.builtin.import_role:
            name: standard
          tags: [standard]

        - name: NTP configuration
          ansible.builtin.import_role:
            name: ntp
          tags: [ntp]

        - name: Pacman configuration
          ansible.builtin.import_role:
            name: pacman
          tags: [pacman]

        - name: Firewall configuration
          ansible.builtin.import_role:
            name: ufw
          when: ufw_enabled
          tags: [ufw]

        - name: KVM configuration
          ansible.builtin.import_role:
            name: kvm
          when: kvm_enabled
          tags: [kvm]

    - name: GUI configuration
      when: gui_enabled
      block:
        - name: Plasma configuration
          ansible.builtin.import_role:
            name: plasma
          tags: [plasma]

        - name: SDDM configuration
          ansible.builtin.import_role:
            name: sddm
          tags: [sddm]

        - name: KDEconnect configuration
          ansible.builtin.import_role:
            name: kdeconnect
          tags: [kdeconnect]

        - name: Bluetooth configuration
          ansible.builtin.import_role:
            name: bluetooth
          tags: [bluetooth]

        - name: Print configuration
          ansible.builtin.import_role:
            name: print
          tags: [print]

        - name: Standard apps configuration
          ansible.builtin.import_role:
            name: standard_apps
          tags: [standard_apps]

        - name: Personal apps configuration
          when: host_type == "personal"
          ansible.builtin.import_role:
            name: personal_apps
          tags: [personal_apps]

    - name: GUI personalization
      when: gui_enabled
      block:
        - name: System settings configuration
          ansible.builtin.import_role:
            name: system_settings
          tags: [system_settings]

        - name: Dolphin configuration
          ansible.builtin.import_role:
            name: dolphin
          tags: [dolphin]

        - name: Kate configuration
          ansible.builtin.import_role:
            name: kate
          tags: [kate]

        - name: Konsole configuration
          ansible.builtin.import_role:
            name: konsole
          tags: [konsole]

        - name: Okular configuration
          ansible.builtin.import_role:
            name: okular
          tags: [okular]

        - name: Gwenview configuration
          ansible.builtin.import_role:
            name: gwenview
          tags: [gwenview]

        - name: Spectacle configuration
          ansible.builtin.import_role:
            name: spectacle
          tags: [spectacle]

        - name: KDEwallet configuration
          ansible.builtin.import_role:
            name: kdewallet
          when:
            - kwl is file
            - salt is file
          tags: [kdewallet]

        - name: Librewolf configuration
          ansible.builtin.import_role:
            name: librewolf
          tags: [librewolf]

        - name: VPN GUI configuration
          ansible.builtin.import_role:
            name: vpn_gui
          tags: [vpn_gui]

        - name: Remmina configuration
          when: host_type == "personal"
          ansible.builtin.import_role:
            name: remmina
          tags: [remmina]

        - name: Signal configuration
          ansible.builtin.import_role:
            name: signal
          tags: [signal]

        - name: Steam configuration
          when: host_type == "personal"
          ansible.builtin.import_role:
            name: steam
          tags: [steam]

        - name: Hardcode_tray configuration
          ansible.builtin.import_role:
            name: hardcode_tray
          tags: [hardcode_tray]

        - name: Clear plasma cache
          ansible.builtin.import_role:
            name: clear_cache
          tags: [clear_cache]

    - name: Kubernetes installation
      when: kubernetes_enabled
      block:
        - name: Install and configure kubernetes
          ansible.builtin.import_role:
            name: kubernetes
          tags: [kubernetes]
        - name: Install and configure nginx-ingress
          ansible.builtin.import_role:
            name: nginx_ingress
          tags: [nginx_ingress]
