---
# Customizing GUI
# --------------------------------------------------------------------

- name: Ensure GUI is installed
  hosts: archinstalled
  become: true

  tasks:

    # Install packages
    # --------------------------------------------------------------------

    - name: Ensure packages are updated
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Ensure packages are installed
      pacman:
        name:
          - latte-dock-git
          - plasma5-applets-window-title-git
          - plasma5-applets-tiledmenu
          - plasma5-applets-window-buttons-git
          - appmenu-gtk-module
          - plasma5-applets-window-appmenu-git
        state: present

    # Set SDDM style
    # --------------------------------------------------------------------

    - name: set style in sddm
      blockinfile:
        path: /etc/sddm.conf.d/kde_settings.conf
        create: true
        mode: 0644
        owner: root
        group: root
        block: |
          [Theme]
          Current=breeze
          CursorTheme=breeze_cursors
