---
- name: Install Arch Linux
  hosts: arch_iso

  vars_files:
    - vars/host_vars.yml

  tasks:
    - name: Abort if the host is not booted from the Arch install media
      fail:
        msg: "This host is not booted from the Arch install media!"
      when: ansible_nodename != 'archiso'

    - name: Set polish keyboard
      command: loadkeys pl

    - name: Ensure NTP is running
      service:
        name: systemd-timesyncd
        state: started
        enabled: true

    - name: Wipe install drive and all its partitions
      command: find /dev -wholename "{{ install_drive }}*" -exec wipefs --force --all {} \;

    - name: Create boot partition
      parted:
        device: '{{ install_drive }}'
        label: gpt
        number: 1
        part_end: 512MiB
        name: boot
        flags: [boot, esp]
        state: present

    - name: Create root partition
      parted:
        device: '{{ install_drive }}'
        label: gpt
        number: 2
        part_start: 512MiB
        name: root
        state: present
