---
# Installation
# --------------------------------------------------------------------

- name: Install Arch Linux
  hosts: archiso

  tasks:

    # First tests and activities
    # --------------------------------------------------------------------

    - name: Abort if the host is not booted from the Arch install media
      fail:
        msg: "This host is not booted from the Arch install media!"
      when: ansible_nodename != 'archiso'

    - name: Set polish keyboard
      command: loadkeys pl

    - name: Ensure NTP is running
      service:
        name: systemd-timesyncd
        state: started
        enabled: true

    # Creating and encrypting partitons
    # --------------------------------------------------------------------

    - name: Wipe install drive and all its partitions
      command: find /dev -wholename "{{ install_drive }}*" -exec wipefs --force --all {} \;

    - name: Create boot partition
      parted:
        device: "{{ install_drive }}"
        label: gpt
        number: 1
        part_end: 512MiB
        name: boot
        flags: [boot, esp]
        state: present

    - name: Create root partition
      parted:
        device: "{{ install_drive }}"
        label: gpt
        number: 2
        part_start: 512MiB
        name: root
        state: present

    - name: Create and open LUKS container with a passphrase
      luks_device:
        device: "{{ install_drive }}{{root_partition_suffix}}"
        passphrase: "{{ crypt_passphrase }}"
        name: cryptroot
        state: opened

    - name: Create FAT32 filesystem in boot partition
      filesystem:
        dev: "{{ install_drive }}{{ boot_partition_suffix }}"
        fstype: vfat
        opts: -F32
        force: yes

    - name: Create ext4 filesystem in root partion
      filesystem:
        dev: /dev/mapper/cryptroot
        fstype: ext4
        force: yes

    # Registering variables
    # --------------------------------------------------------------------

    - name: Get UUID for boot filesystem
      command: blkid -s UUID -o value "{{ install_drive }}{{ boot_partition_suffix }}"
      register: boot_uuid
      changed_when: false

    - name: Get UUID for root filesystem
      command: blkid -s UUID -o value "{{ install_drive }}{{ root_partition_suffix }}"
      register: root_uuid
      changed_when: false

    - name: Get UUID for cryptroot filesystem
      command: blkid -s UUID -o value /dev/mapper/cryptroot
      register: cryptroot_uuid
      changed_when: false

    - name: Get tpm driver
      shell: systemd-cryptenroll --tpm2-device=list |& grep -o "tpm_.*"
      ignore_errors: true
      register: tpm_driver
      changed_when: false

    # Mounting filesystems
    # --------------------------------------------------------------------

    - name: Mount root filesystem
      mount:
        path: /mnt
        src: /dev/mapper/cryptroot
        fstype: ext4
        state: mounted

    - name: Create mountpoint for boot volume
      file:
        path: /mnt/boot
        state: directory

    - name: Mount boot filesystem
      mount:
        path: /mnt/boot
        src: UUID={{ boot_uuid.stdout }}
        fstype: vfat
        state: mounted

    # Installing basic packages
    # --------------------------------------------------------------------

    - name: Run pacstrap
      command: pacstrap /mnt base base-devel linux-zen linux-zen-headers linux-firmware vim nano sudo networkmanager e2fsprogs dosfstools ntfs-3g intel-ucode git openssh python python-pexpect sudo sbctl tpm2-tools {{ add_packages }}

    # Generating fstab
    # --------------------------------------------------------------------

    - name: Generate blank fstab
      command: genfstab -U /mnt >> /mnt/etc/fstab

    - name: Add root volume to fstab
      mount:
        fstab: /mnt/etc/fstab
        path: /
        src: UUID={{ root_uuid.stdout }}
        fstype: ext4
        opts: defaults,noatime
        passno: "1"
        state: present

    - name: Add boot volume to fstab
      mount:
        fstab: /mnt/etc/fstab
        path: /boot
        src: UUID={{ boot_uuid.stdout }}
        fstype: vfat
        opts: defaults
        passno: "2"
        state: present

    # Configuring time and locale
    # --------------------------------------------------------------------

    - name: Set local timezone
      command: arch-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/Warsaw /etc/localtime

    - name: Set hardware clock from system clock
      command: arch-chroot /mnt hwclock --systohc

    - name: Configure locale.gen
      lineinfile:
        dest: /mnt/etc/locale.gen
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
      loop:
        - {regex: en_US\.UTF-8 UTF-8, line: en_US.UTF-8 UTF-8}
        - {regex: en_GB\.UTF-8 UTF-8, line: en_GB.UTF-8 UTF-8}
        - {regex: pl_PL\.UTF-8 UTF-8, line: pl_PL.UTF-8 UTF-8}

    - name: Create locale.conf (en_PL)
      copy:
        src: files/locale_en_PL.conf
        dest: /mnt/etc/locale.conf
      when: system_lang == "en_PL"

    - name: Create locale.conf (pl_PL)
      copy:
        src: files/locale_pl_PL.conf
        dest: /mnt/etc/locale.conf
      when: system_lang == "pl_PL"

    - name: Set keymap
      copy:
        content: "KEYMAP=pl"
        dest: /mnt/etc/vconsole.conf

    - name: Generate locales
      command: arch-chroot /mnt locale-gen

    # Setting hostname
    # --------------------------------------------------------------------

    - name: Set hostname
      copy:
        content: "{{ hostname }}"
        dest: /mnt/etc/hostname

    - name: Set hosts
      copy:
        content: |
          127.0.0.1   localhost
          ::1         localhost
          127.0.1.1   {{ hostname }}.{{ localdomain }}  {{ hostname }}
        dest: /mnt/etc/hosts

    # Setting disk labels
    # --------------------------------------------------------------------

    - name: Set label for boot partition
      command: arch-chroot /mnt fatlabel {{ install_drive }}{{ boot_partition_suffix }} "{{ boot_partition_label }}"

    - name: Set label for root partition
      command: arch-chroot /mnt cryptsetup config --label="{{ root_partition_label }}" {{ install_drive }}{{ root_partition_suffix }}

    # Platform specific modifications
    # --------------------------------------------------------------------

    - name: Make sure pacman hook dir exisits
      file:
        path: /mnt/etc/pacman.d/hooks
        state: directory

    - name: Create pacman hook for updating initramfs after NVIDIA driver update
      copy:
        src: files/nvidia.hook
        dest: /mnt/etc/pacman.d/hooks/nvidia.hook
      when: gpu_manufacturer == "nvidia"

    - name: Enable qemu-guest-agent service
      command: arch-chroot /mnt systemctl enable qemu-guest-agent.service
      when: gpu_manufacturer == "virt"

    - name: Leave a file to check gpu_manufacturer
      copy:
        content: "{{ gpu_manufacturer }}"
        dest: /mnt/usr/local/etc/gpu_manufacturer


    # systemd-boot configuration
    # --------------------------------------------------------------------

    - name: Install systemd-boot
      command: arch-chroot /mnt bootctl install

    - name: Create unified kernel image preset
      copy:
        src: files/linux-zen.preset
        dest: /mnt/etc/mkinitcpio.d/linux-zen.preset

    - name: Configure kernel parametres
      copy:
        content: rd.luks.name={{ root_uuid.stdout }}=cryptroot rd.luks.options={{ root_uuid.stdout }}=tpm2-device=auto root=/dev/mapper/cryptroot rw nowatchdog nosgx {{ kernel_cmd }}
        dest: /mnt/etc/kernel/cmdline

    - name: Enable update systemd-boot service (as backup)
      command: arch-chroot /mnt systemctl enable systemd-boot-update.service

    - name: Create pacman hook for updating systemd-boot after systemd update
      copy:
        src: files/50-systemd-boot.hook
        dest: /mnt/etc/pacman.d/hooks/50-systemd-boot.hook

    # mkinitcpio configuration
    # --------------------------------------------------------------------

    - name: Add mkinitcpio.conf hooks
      lineinfile:
        dest: /mnt/etc/mkinitcpio.conf
        regexp: ^HOOKS=
        line: HOOKS=(base systemd sd-encrypt autodetect keyboard sd-vconsole modconf block filesystems fsck)

    - name: Add mkinitcpio.conf modules
      lineinfile:
        dest: /mnt/etc/mkinitcpio.conf
        regexp: ^MODULES=
        line: MODULES=({{ mkinicpio_modules }} {{ tpm_driver.stdout }})

    - name: Create new initramfs
      command: arch-chroot /mnt mkinitcpio -P

    # SecureBoot configuration
    # --------------------------------------------------------------------

    - name: Create SecureBoot keys
      command: arch-chroot /mnt sbctl create-keys

    - name: Enroll SecureBoot keys
      command: arch-chroot /mnt sbctl enroll-keys --microsoft

    - name: Sign efi files and boot loader
      command: arch-chroot /mnt {{ item }}
      loop:
        - sbctl sign --save /boot/EFI/Linux/archlinux-linux-zen.efi
        - sbctl sign --save /boot/EFI/Linux/archlinux-linux-zen-fallback.efi
        - sbctl sign --save /boot/EFI/BOOT/BOOTX64.EFI
        - sbctl sign --save /boot/EFI/systemd/systemd-bootx64.efi
        - sbctl sign --save /boot/vmlinuz-linux-zen

    # Enable services
    # --------------------------------------------------------------------

    - name: Enable dns service
      command: arch-chroot /mnt systemctl enable systemd-resolved

    - name: Enable network service
      command: arch-chroot /mnt systemctl enable NetworkManager

    - name: Enable network service
      command: arch-chroot /mnt systemctl enable sshd

    # Create user
    # --------------------------------------------------------------------

    - name: Create user account
      command: arch-chroot /mnt useradd --create-home --user-group --groups wheel {{ user_name }} --password {{ user_password }}

    - name: Create user's ssh directory
      file:
        path: /mnt/home/{{ user_name }}/.ssh
        state: directory

    - name: Set mode, owner, and group on user's ssh directory
      command: arch-chroot /mnt {{ item }}
      loop:
        - chmod 0700 /home/{{ user_name }}/.ssh
        - chown {{ user_name }}:{{ user_name }} /home/{{ user_name }}/.ssh

    - name: Copy over ssh pub keys as an authorized keys
      copy:
        src: "{{ ssh_pub_keys }}"
        dest: /mnt/home/{{ user_name }}/.ssh/authorized_keys

    - name: Set mode, owner, and group on user's authorized_key file
      command: arch-chroot /mnt {{ item }}
      loop:
        - chmod 0600 /home/{{ user_name }}/.ssh/authorized_keys
        - chown {{ user_name }}:{{ user_name }} /home/{{ user_name }}/.ssh/authorized_keys

    - name: Give sudo access to wheel group
      copy:
        content: "%wheel      ALL=(ALL) ALL"
        dest: /mnt/etc/sudoers.d/wheel
        validate: /usr/sbin/visudo --check --file=%s

    - name: Force public key authentication
      blockinfile:
        path: /mnt/etc/ssh/sshd_config
        insertafter: EOF
        block: |
          # Modified by Arch-Ansible-Install
          # Author Drik.IT
          PasswordAuthentication no
          AuthenticationMethods publickey

    # Reboot and wait
    # --------------------------------------------------------------------

    - name: Reboot archiso and ignore errors
      reboot:
        reboot_timeout: 60
      ignore_errors: true

# Post-Installation
# --------------------------------------------------------------------

- name: Post-Installation
  hosts: archinstalled
  gather_facts: no

  tasks:

    # Waiting and gathering facts
    # --------------------------------------------------------------------

    - name: Wait for SSH to respond on host
      wait_for_connection:

    - name: Gather facts
      setup:

    # Enrolling TPM
    # --------------------------------------------------------------------

    - name: Enroll TPM
      expect:
        command: systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+7 {{ install_drive }}{{ root_partition_suffix }}
        responses:
          (?i)passphrase: "{{ crypt_passphrase }}"
      no_log: true
      become: true

    # Clean-up
    # --------------------------------------------------------------------

    - name: Disable root
      command: passwd -l root
      become: true

    - name: Reboot archinstalled
      reboot:
      become: true
