---

- name: Install Arch Linux
  hosts: install_medium
  tags: [installation]
  tasks:

    - name: Installation using install_medium
      ansible.builtin.import_role:
        name: installation

- name: Post-Installation
  hosts: "{{ hostname | default('hostname') }}"
  gather_facts: false
  tags: [post_installation]
  tasks:

    - name: Wait for SSH to respond on host
      ansible.builtin.wait_for_connection:
        timeout: 9000

    - name: Gather facts
      ansible.builtin.setup:

    - name: Enroll TPM
      ansible.builtin.expect:
        command: systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+1+7+8 {{ installation_drive.name }}{{ installation_drive.root_partition_suffix }}
        responses:
          (?i)passphrase: "{{ crypt_passphrase }}"
      no_log: true
      become: true
      failed_when: false

    - name: Disable root
      ansible.builtin.command: passwd -l root
      changed_when: true
      become: true

    - name: Reboot archinstalled
      ansible.builtin.reboot:
      become: true
