---
# Installing and configuring latte-dock
# --------------------------------------------------------------------

- name: Ensure latte-dock is installed and configured
  hosts: archinstalled
  become: true

  tasks:

    # Install packages
    # --------------------------------------------------------------------

    - name: Ensure packages are updated
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Ensure packages are installed
      pacman:
        name:
          - latte-dock-git
          - plasma5-applets-window-title-git
          - plasma5-applets-tiledmenu
          - plasma5-applets-window-buttons-git
          - appmenu-gtk-module
          - plasma5-applets-window-appmenu-git
        state: present
