---
# Configuring printing
# --------------------------------------------------------------------

- name: Ensure basic software is installed
  hosts: archinstalled
  become: true

  tasks:

    # Install packages
    # --------------------------------------------------------------------

    - name: Ensure packages are updated
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Ensure packages are installed
      pacman:
        name:
          - cups
          - cups-pdf
          - system-config-printer
          - ghostscript
          - gsfonts
          - foomatic-db-engine
          - foomatic-db
          - foomatic-db-nonfree
          - foomatic-db-nonfree-ppds
        state: present

    # Configure printing
    # --------------------------------------------------------------------

    - name: Ensure cups socket is enabled
      systemd:
        name: cups.socket
        enabled: yes
      notify: set-papersize

    - name: Set paper size
      copy:
        content: a4
        dest: /etc/papersize

  # Handlers
  # --------------------------------------------------------------------

  handlers:

    - name: set-papersize
      command: paperconfig -p a4
