---

- name: Init kube cluster
  ansible.builtin.command: >
    kubeadm init
    --cri-socket=unix:/run/containerd/containerd.sock
    --pod-network-cidr='{{ kubernetes_pod_network }}'
  changed_when: true
  when: false

- name: Create kubectl config dir
  ansible.builtin.file:
    dest: /root/.kube
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Configure kubectl for root
  ansible.builtin.copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: "0600"
    owner: root
    group: root

- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted

- name: Install pod network addon
  ansible.builtin.command: cilium-cli install
  changed_when: true

- name: Register join token
  ansible.builtin.command: kubeadm token list -o json
  register: kubeadm_token_result
  changed_when: true

- name: Output join token
  ansible.builtin.debug:
    msg: "{{ kubeadm_token_result.stdout | to_json | json_query('[0].token') }}"
