---

- name: Ensure packages are updated
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Ensure basic kubernetes software is installed
  community.general.pacman:
    name:
      - kubeadm
      - kubelet
      - containerd
    state: present

- name: Ensure control-plane kubernetes software is installed
  community.general.pacman:
    name:
      - kubectl
    state: present
  when: kubernetes_control_plane_node

- name: Add required modules
  ansible.builtin.template:
    src: k8s-modules.conf.j2
    dest: /etc/modules-load.d/k8s.conf
    mode: "0644"
    owner: root
    group: root

- name: Make sure modules are loaded
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ kubernetes_modprobe_modules }}"

- name: Add and load required params
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: true
  loop: "{{ kubernetes_sysctl_params }}"

- name: Enable and start containerd service
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true
