---

- name: Ensure packages are updated
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Ensure vpn software and networkmanager integrations are installed
  community.general.pacman:
    name:
      - networkmanager-l2tp
      - networkmanager-strongswan
      - networkmanager-pptp
      - strongswan
      - networkmanager-openconnect
      - openconnect
      - networkmanager-fortisslvpn
      - openfortivpn
      - systemd-resolvconf
    state: present

- name: Touch l2tp config file to allow the service to start
  ansible.builtin.file:
    path: /etc/xl2tpd/xl2tpd.conf
    owner: root
    group: root
    mode: "0644"
    state: touch

- name: Enable and start xl2tpd service
  ansible.builtin.systemd:
    name: xl2tpd
    state: started
    enabled: true
