---

- name: Create nfs user
  ansible.builtin.user:
    name: "{{ nfs_user_name }}"
    uid: "{{ nfs_user_uid }}"

- name: Create nfs root dir
  ansible.builtin.file:
    path: "{{ nfs_server_root }}"
    owner: "{{ nfs_user_name }}"
    group: "{{ nfs_user_name }}"
    mode: "0750"
    state: directory

- name: Mask reduntant services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
    masked: true
  loop:
    - nfs-server.service
    - rpcbind.service
    - rpcbind.socket

- name: Enable and start nfs-server
  ansible.builtin.systemd:
    name: nfsv4-server.service
    enabled: true
    state: started

- name: Add bind mounts to fstab
  ansible.posix.mount:
    fstab: /etc/fstab
    path: "{{ item.mount_point }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fstype | default(nfs_default_fstype) }}"
    opts: "{{ item.bind_options | default(nfs_default_bind_options) }}"
    state: mounted
  loop: "{{ nfs_server_shares }}"

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Set permissions for shares
  ansible.builtin.file:
    dest: "{{ nfs_server_root }}"
    owner: "{{ nfs_user_name }}"
    group: "{{ nfs_user_name }}"
    recurse: true
    mode: u=rw-x+X,g=r-x+X,o=
  when: nfs_change_permissions

- name: Set exports file
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify: Reload nfs
