---

- name: Ensure dolphin is installed
  community.general.pacman:
    name:
      - dolphin
    state: present

- name: Set dolphinrc (dolphin settings)
  ansible.builtin.copy:
    src: dolphinrc
    dest: /home/{{ user_name }}/.config/dolphinrc
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"

- name: Ensure view_properties directory exists
  ansible.builtin.file:
    path: /home/{{ user_name }}/.local/share/dolphin/view_properties/global/
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
    recurse: true

- name: Set dolphistaterc (dolphin state)
  ansible.builtin.copy:
    src: dolphinstaterc
    dest: /home/{{ user_name }}/.local/share/dolphin/dolphinstaterc
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"

- name: Set view mode to details in dolphin
  ansible.builtin.copy:
    src: directory
    dest: /home/{{ user_name }}/.local/share/dolphin/view_properties/global/.directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"

- name: Hide unused items in places (dolphin)
  community.general.xml:
    path: /home/{{ user_name }}/.local/share/user-places.xbel
    xpath: "{{ item }}"
    value: "true"
  loop:
    - /xbel/info/metadata/GroupState-RecentlySaved-IsHidden
    - /xbel/info/metadata/GroupState-SearchFor-IsHidden

- name: Delete junk folders from places
  community.general.xml:
    path: /home/{{ user_name }}/.local/share/user-places.xbel
    xpath: "{{ item }}"
    state: absent
  loop:
    - /xbel/bookmark[title='Music']
    - /xbel/bookmark[title='Pictures']
    - /xbel/bookmark[title='Videos']
    - /xbel/bookmark[title='Muzyka']
    - /xbel/bookmark[title='Obrazy']
    - /xbel/bookmark[title='Wideo']

- name: Hide duplicate disk in places
  community.general.xml:
    path: /home/{{ user_name }}/.local/share/user-places.xbel
    xpath: /xbel/separator/info/metadata[UDI='/org/freedesktop/UDisks2/block_devices/dm_2d0']/IsHidden
    value: "true"
  register: dolphin_xml_result
  changed_when:
    - 'dolphin_xml_result.msg is defined or dolphin_xml_result.changed == true'
  failed_when: false
  notify: Add block device

- name: Set trash to no limit
  ansible.builtin.template:
    src: ktrashrc.j2
    dest: /home/{{ user_name }}/.config/ktrashrc
    mode: "0600"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
