---

- name: Ensure signal is installed
  community.general.pacman:
    name:
      - signal-desktop
    state: present

- name: Edit signal-desktop shortcut to start to tray
  ansible.builtin.replace:
    path: /usr/share/applications/signal-desktop.desktop
    regexp: '^Exec=.*'
    replace: 'Exec=LC_ALL=pl signal-desktop --use-tray-icon --start-in-tray -- %u'

- name: Make sure autostart dir exists
  ansible.builtin.file:
    path: /home/{{ user_name }}/.config/autostart
    state: directory
    mode: "0755"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Autostart signal
  ansible.builtin.copy:
    src: signal-desktop.desktop
    dest: /home/{{ user_name }}/.config/autostart/signal-desktop.desktop
    mode: "0644"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
