---

- name: Ensure packages are updated
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Ensure bluez is installed
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
    state: present

- name: Enable bluetooth service
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
