---

- name: Ensure packages are updated
  pacman:
    update_cache: true
    upgrade: true

- name: Ensure bluez is installed
  pacman:
    name:
      - bluez
      - bluez-utils
    state: present

- name: Enable bluetooth service
  systemd:
    name: bluetooth
    enabled: true
