---

- name: Ensure packages are updated
  pacman:
    update_cache: true
    upgrade: true

- name: Ensure kate is installed
  pacman:
    name:
      - kate
    state: present

- name: Set katerc (kate settings)
  copy:
    src: katerc
    dest: /home/{{ user_name }}/.config/katerc
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600

- name: Make sure sessions directory exists
  file:
    path: /home/{{ user_name }}/.local/share/kate/sessions
    state: directory
    recurse: true

- name: Set kate session
  copy:
    src: Notepad.katesession
    dest: /home/{{ user_name }}/.local/share/kate/sessions/Notepad.katesession
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600

- name: Always start Notepad session
  lineinfile:
    dest: /usr/share/applications/org.kde.kate.desktop
    regexp: Exec=kate -b %U
    line: Exec=kate -b %U --start Notepad
    backrefs: true

- name: Make sure syntax directory exists
  file:
    path: /home/{{ user_name }}/.local/share/org.kde.syntax-highlighting/syntax
    state: directory
    recurse: true
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755

- name: Copy Jinja2 files for Ansible syntax
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user_name }}/.local/share/org.kde.syntax-highlighting/syntax/{{ item }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0644
  loop:
    - yaml-jinja2.xml
    - jinja2.xml
    - javascript-jinja2.xml
    - html-jinja2.xml
    - css-jinja2.xml
