---

- name: Ensure packages are installed
  community.general.pacman:
    name:
      - pacman-contrib
      - reflector
    state: present

- name: Ensure paccache timer is enabled and started
  ansible.builtin.systemd:
    name: paccache.timer
    enabled: true
    state: started

- name: Ensure paccache.service.d directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/paccache.service.d/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Ensure paccache.service override exists
  ansible.builtin.copy:
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/paccache -rk1 ; /usr/bin/paccache -ruk0
    dest: /etc/systemd/system/paccache.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: Daemon reload

- name: Ensure pacman config is correct
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: "0644"
  notify: Update cache

- name: Import key for archzfs repo
  community.general.pacman_key:
    id: DDF7DB817396A49B2A2723F7403BD972F75D9D76
    url: https://archzfs.com/archzfs.gpg
    state: present

- name: Ensure reflector config is correct
  ansible.builtin.lineinfile:
    dest: /etc/xdg/reflector/reflector.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^#?.?--country", line: "--country Poland,Germany,France" }
    - { regexp: "^#?.?--sort", line: "--sort rate" }

- name: Ensure reflector timer is enabled and started
  ansible.builtin.systemd:
    name: reflector.timer
    enabled: true
    state: started
  notify: Run reflector

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
