---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: dagonite-empire
  namespace: dagonite-empire
spec:
  chart:
    spec:
      chart: dagonite-empire
      version: 0.1.*
      sourceRef:
        kind: HelmRepository
        name: drik-homelab
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: dagonite-empire
  valuesFrom:
  - kind: ConfigMap
    name: dagonite-empire-values
    valuesKey: values.yaml
  - kind: Secret
    name: dagonite-empire-secret-values
    valuesKey: notesPlain
