---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dagonite-empire-values
  namespace: dagonite-empire
data:
  values.yaml: |-
    image:
      repository: docker.io/drikqlis/dagonite-empire # {"$imagepolicy": "flux-system:dagonite-empire:name"}
      tag: latest # {"$imagepolicy": "flux-system:dagonite-empire:tag"}

    replicaCount: 1

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: dagonite-empire.drik.it
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: dagonite-empire-certs
          hosts:
            - dagonite-empire.drik.it

    postgresql:
      clusterDomain: cluster.drik.it
