---

- name: Ensure spectacle is installed
  community.general.pacman:
    name:
      - spectacle
    state: present

- name: Set spectaclerc (spectacle settings)
  ansible.builtin.template:
    src: spectaclerc.j2
    dest: /home/{{ user_name }}/.config/spectaclerc
    mode: "0600"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Change spectacle shortcuts
  ansible.builtin.lineinfile:
    dest: /home/{{ user_name }}/.config/kglobalshortcutsrc
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
    backrefs: true
  loop:
    - {regex: "RectangularRegionScreenShot=", line: "RectangularRegionScreenShot=Meta+Shift+S,Meta+Shift+Print,Capture Rectangular Region"}
    - {regex: "WindowUnderCursorScreenShot=", line: "WindowUnderCursorScreenShot=Meta+Ctrl+S,Meta+Ctrl+Print,Capture Window Under Cursor"}
