---

- name: Install and configure sanoid
  ansible.builtin.import_tasks: sanoid.yml
  tags: [sanoid_configure]

- name: Configure syncoid
  ansible.builtin.import_tasks: syncoid.yml
  when: sanoid_syncoid_enabled
  tags: [syncoid_configure]
