apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: dagonite-empire-dev
  namespace: dagonite-empire-dev
spec:
  upgrade:
    force: true
  chart:
    spec:
      chart: dagonite-empire
      version: 0.2.*
      sourceRef:
        kind: HelmRepository
        name: drik-homelab
        namespace: flux-system
  interval: 10m
  timeout: 5m
  releaseName: dagonite-empire-dev
  values:
    image:
      repository: ghcr.io/krystiankempski/dagoniteempire # {"$imagepolicy": "flux-system:dagonite-empire-dev:name"}
      tag: dev.2024-11-18T21-43-56-master # {"$imagepolicy": "flux-system:dagonite-empire-dev:tag"}
  valuesFrom:
  - kind: ConfigMap
    name: dagonite-empire-dev-values
    valuesKey: values.yaml
  - kind: Secret
    name: dagonite-empire-dev-secret-values
    valuesKey: notesPlain
