---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dagonite-empire-dev-secret-values
  namespace: dagonite-empire-dev
spec:
  itemPath: "vaults/Kubernetes/items/dagonite-empire-dev-secret-values"
