apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: dagonite-empire-dev
  namespace: dagonite-empire-dev
spec:
  upgrade:
    force: true
  chart:
    spec:
      chart: dagonite-empire
      version: 0.1.*
      sourceRef:
        kind: HelmRepository
        name: drik-homelab
        namespace: flux-system
  interval: 10m
  timeout: 5m
  releaseName: dagonite-empire-dev
  values:
    image:
      repository: docker.io/drikqlis/dagonite-empire # {"$imagepolicy": "flux-system:dagonite-empire-dev:name"}
      tag: dev.2024-10-31T17-44-36-master # {"$imagepolicy": "flux-system:dagonite-empire-dev:tag"}
    postgresql:
      commonLabels:
        rollme: "{{ randAlphaNum 5 | quote }}"
  valuesFrom:
  - kind: ConfigMap
    name: dagonite-empire-dev-values
    valuesKey: values.yaml
  - kind: Secret
    name: dagonite-empire-dev-secret-values
    valuesKey: notesPlain
