---

- name: Set kdeglobals (global theme, single click, file dialog)
  copy:
    src: kdeglobals
    dest: /home/{{ user_name }}/.config/kdeglobals
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Set kwinrc (disable border buttons, borderless maximized, meta shortcut to krunner, night color)
  copy:
    src: kwinrc
    dest: /home/{{ user_name }}/.config/kwinrc
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Set khotkeysrc (type-clip, system monitor)
  copy:
    src: khotkeysrc
    dest: /home/{{ user_name }}/.config/khotkeysrc
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Delete junk home folders
  file:
    path: /home/{{ user_name }}/{{ item }}
    state: absent
  loop:
    - Videos
    - Music
    - Pictures
    - Templates
    - Public
    - Wideo
    - Muzyka
    - Obrazy
    - Szablony
    - Publiczne

- name: Disable browser integration reminder service
  replace:
    path: /home/{{ user_name }}/.config/kded5rc
    regexp: '^\[Module-browserintegrationreminder\]\nautoload=.*'
    replace: '[Module-browserintegrationreminder]\nautoload=false'
  register: result
  ignore_errors: yes
  changed_when:
    - 'result.msg is defined or result.changed == true'
  failed_when: false
  notify: set-kded5rc

- name: Set ksmserverrc (confirm logout off, start with empty session)
  copy:
    src: ksmserverrc
    dest: /home/{{ user_name }}/.config/ksmserverrc
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Set krunnerrc (disable browser history, tabs and bookmarks search)
  copy:
    src: krunnerrc
    dest: /home/{{ user_name }}/.config/krunnerrc
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Make sure KDE dir exists
  file:
    path: /home/{{ user_name }}/.config/KDE
    state: directory
    mode: 0755
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Set Sonnet.conf (spell check settings)
  copy:
    src: Sonnet.conf
    dest: /home/{{ user_name }}/.config/KDE/Sonnet.conf
    mode: 0644
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Set kcminputrc (numlock on startup, mouse acceleration)
  copy:
    src: kcminputrc
    dest: /home/{{ user_name }}/.config/kcminputrc
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Set kxkbrc (keyboard layouts)
  copy:
    src: kxkbrc
    dest: /home/{{ user_name }}/.config/kxkbrc
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Set klipperrc (clipboard settings)
  copy:
    src: klipperrc
    dest: /home/{{ user_name }}/.config/klipperrc
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Set powermanagementprofilesrc (power settings)
  copy:
    src: powermanagementprofilesrc
    dest: /home/{{ user_name }}/.config/powermanagementprofilesrc
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Set xdg-desktop-portal-kderc (file dialog for Firefox etc)
  copy:
    src: xdg-desktop-portal-kderc
    dest: /home/{{ user_name }}/.config/xdg-desktop-portal-kderc
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Set xdg-desktop-portal-kderc (file dialog for Firefox etc)
  copy:
    src: plasmashellrc
    dest: /home/{{ user_name }}/.config/plasmashellrc
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Set xdg-desktop-portal-kderc (file dialog for Firefox etc)
  copy:
    src: systemsettingsrc
    dest: /home/{{ user_name }}/.config/systemsettingsrc
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Set kritarc (file dialog for Krita)
  copy:
    src: kritarc
    dest: /home/{{ user_name }}/.config/kritarc
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
