---

- name: Ssh client tasks
  ansible.builtin.import_tasks: ssh_client.yml
  tags: [ssh_client]
  when: ssh_client_enabled

- name: Ssh server tasks
  ansible.builtin.import_tasks: ssh_server.yml
  tags: [ssh_server]
