---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      version: 1.15.*
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: cilium
  valuesFrom:
  - kind: ConfigMap
    name: cilium-values
    valuesKey: values.yaml
