---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  chart:
    spec:
      chart: immich
      version: 0.4.*
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: immich
  valuesFrom:
  - kind: ConfigMap
    name: immich-values
    valuesKey: values.yaml
  - kind: Secret
    name: immich-secret-values
    valuesKey: notesPlain
