---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-values
  namespace: immich
data:
  values.yaml: |-
    env:
      DB_PASSWORD: null
    envFrom:
    - secretRef:
        name: immich-secret-values

    immich:
      persistence:
        library:
          existingClaim: immich-library

    postgresql:
      enabled: true
      clusterDomain: cluster.drik.it
      global:
        postgresql:
          auth:
            postgresPassword: ""
            username: "immich"
            password: ""
            database: "immichdb"
            existingSecret: "immich-secret-values"
            secretKeys:
              adminPasswordKey: DB_PASSWORD_ADMIN
              userPasswordKey: DB_PASSWORD
              replicationPasswordKey: ""

    redis:
      enabled: true
      clusterDomain: cluster.drik.it
      auth:
        enabled: false

    server:
      enabled: true
      ingress:
        main:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - host: immich.drik.it
              paths:
                - path: "/"
          tls:
            - hosts:
              - immich.drik.it
              secretName: immich-certs

    microservices:
      enabled: true

    machine-learning:
      enabled: true
      persistence:
        cache:
          enabled: true
          size: 10Gi
          accessMode: ReadWriteMany
