---
# kdewallet
kdewallet_salt: "files/users/{{ user_name }}/kdewallet.salt"
kdewallet_kwl: "files/users/{{ user_name }}/kdewallet.kwl"

gui_enabled: false
kvm_enabled: false
kubernetes_enabled: false
ufw_enabled: true
zfs_enabled: false

network_interface: eno1

mkinitcpio_hooks: "{{ mkinitcpio_hooks_base + ' zfs' if zfs_enabled else '' }}"
mkinitcpio_hooks_base: "base systemd sd-encrypt autodetect keyboard sd-vconsole modconf block filesystems fsck"
