---
# kdewallet
kdewallet_salt: "files/users/{{ user_name }}/kdewallet.salt"
kdewallet_kwl: "files/users/{{ user_name }}/kdewallet.kwl"

installation_zfs_datasets:
  - name: root
    properties: -o mountpoint=/ -o canmount=noauto
  - name: home
    properties: -o mountpoint=/home

gui_enabled: false
kvm_enabled: false
nfs_enabled: false
kubernetes_enabled: false
ufw_enabled: true
sanoid_enabled: true
zfs_additional_drives_enabled: false
pacman_local_mirror_enabled: true

network_interface: eno1
network_bond_enabled: false
network_bond_slaves:
  - eno1
  - eno2
