---

- name: Limit log size to 200mb
  ansible.builtin.lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: ^#?SystemMaxUse=
    line: SystemMaxUse=200M

- name: Set vim as default editor
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: EDITOR=vim

- name: Enable fstrim.timer service for SSD
  ansible.builtin.systemd:
    name: fstrim.timer
    state: started
    enabled: true

- name: Ensure basic software is installed
  community.general.pacman:
    name:
      - bind
      - inetutils
      - base
      - base-devel
      - linux
      - linux-headers
      - linux-firmware
      - vim
      - vi
      - less
      - rsync
      - netcat
      - wget
      - nano
      - sudo
      - htop
      - networkmanager
      - e2fsprogs
      - dosfstools
      - ntfs-3g
      - intel-ucode
      - git
      - openssh
      - python
      - python-pexpect
      - python-lxml
      - sudo
      - sbctl
      - tpm2-tools
      - bash-completion
    state: present
