---

- block:

  - name: Ensure packages are updated
    pacman:
      update_cache: yes
      upgrade: yes

  - name: Ensure sddm is installed
    pacman:
      name:
        - sddm
      state: present

  - name: Make sure sddm.conf.d dir exisits
    file:
      path: /etc/sddm.conf.d
      state: directory
      mode: 0755
      owner: root
      group: root

  - name: Ensure sddm kde settings are applied
    copy:
      src: kde_settings.conf
      dest: /etc/sddm.conf.d/kde_settings.conf
      mode: 0644
      owner: root
      group: root

  - name: Enable sddm service
    systemd:
      name: sddm
      state: started
      enabled: yes

  become: yes
