---

- name: Ensure kate is installed
  community.general.pacman:
    name:
      - kate
    state: present

- name: Set katerc (kate settings)
  ansible.builtin.copy:
    src: katerc
    dest: /home/{{ user_name }}/.config/katerc
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"

- name: Make sure sessions directory exists
  ansible.builtin.file:
    path: /home/{{ user_name }}/.local/share/kate/sessions
    state: directory
    recurse: true

- name: Set kate session
  ansible.builtin.copy:
    src: Notepad.katesession
    dest: /home/{{ user_name }}/.local/share/kate/sessions/Notepad.katesession
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"

- name: Always start Notepad session
  ansible.builtin.lineinfile:
    dest: /usr/share/applications/org.kde.kate.desktop
    regexp: Exec=kate -b %U
    line: Exec=kate -b %U --start Notepad
    backrefs: true
