---

- name: Delete user cache
  ansible.builtin.file:
    path: /home/{{ user_name }}/.cache
    state: absent

- name: Recrate user cache folder
  ansible.builtin.file:
    path: /home/{{ user_name }}/.cache
    state: directory
    mode: "0755"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Delete SDDM cache
  ansible.builtin.file:
    path: /var/lib/sddm/.cache
    state: absent

- name: Recrate SDDM cache folder
  ansible.builtin.file:
    path: /var/lib/sddm/.cache
    state: directory
    mode: "0755"
    owner: sddm
    group: sddm
