---

- name: Wipe install drive and all its partitions
  ansible.builtin.command: find /dev -wholename "{{ install_drive }}*" -exec wipefs --force --all {} \;
  changed_when: true

- name: Create boot partition
  community.general.parted:
    device: "{{ install_drive }}"
    label: gpt
    number: 1
    part_end: 512MiB
    name: boot
    flags: [boot, esp]
    state: present

- name: Create FAT32 filesystem in boot partition
  community.general.filesystem:
    dev: "{{ install_drive }}{{ boot_partition_suffix }}"
    fstype: vfat
    opts: -F32
    force: true

- name: Create root partition
  community.general.parted:
    device: "{{ install_drive }}"
    label: gpt
    number: 2
    part_start: 512MiB
    name: root
    state: present

- name: Create and open LUKS container with a passphrase
  community.crypto.luks_device:
    device: "{{ install_drive }}{{ root_partition_suffix }}"
    passphrase: "{{ crypt_passphrase }}"
    name: cryptroot
    state: opened

- name: Create btrfs filesystem in root partion
  community.general.filesystem:
    dev: /dev/mapper/cryptroot
    fstype: btrfs
    force: true

- name: Create subvolumes
  community.general.btrfs_subvolume:
    filesystem_device: /dev/mapper/cryptroot
    name: /{{ item.name }}
    default: "{{ item.default }}"
  loop: "{{ btrfs_subvolumes }}"

- name: Mount subvolumes
  ansible.posix.mount:
    path: /mnt{{ item.mount_point }}
    src: /dev/mapper/cryptroot
    fstype: btrfs
    opts: subvol={{ item.name }}
    state: mounted
  loop: "{{ btrfs_subvolumes }}"
