---

- name: Wipe install drive and all its partitions
  ansible.builtin.command: find /dev -wholename "{{ installation_drive.name }}*" -exec wipefs --force --all {} \;
  changed_when: true

- name: Install zfs on archiso # noqa risky-shell-pipe command-instead-of-module
  ansible.builtin.shell: curl -s https://raw.githubusercontent.com/eoli3n/archiso-zfs/master/init | bash
  changed_when: true

- name: Ensure python-pexpect is installed
  community.general.pacman:
    name:
      - python-pexpect
    state: present

- name: Create EFI partition
  community.general.parted:
    device: "{{ installation_drive.name }}"
    label: gpt
    number: 1
    part_end: 512MiB
    name: efi
    flags: [esp]
    state: present

- name: Create FAT32 filesystem in EFI partition
  community.general.filesystem:
    dev: "{{ installation_drive.name }}{{ installation_drive.efi_partition_suffix }}"
    fstype: vfat
    opts: -F32
    force: true

- name: Create root partition
  community.general.parted:
    device: "{{ installation_drive.name }}"
    label: gpt
    number: 2
    part_start: 512MiB
    name: root
    state: present

- name: Create encrypted zpool
  ansible.builtin.expect:
    command: >
      zpool create -f -o ashift=12
      -O acltype=posixacl
      -O relatime=on
      -o autotrim=on
      -o autoexpand=on
      -O xattr=sa
      -O dnodesize=legacy
      -O normalization=formD
      -O mountpoint=none
      -O canmount=off
      -O devices=off
      -R /mnt
      -O compression={{ installation_zfs_zpool_compression }}
      -O encryption=aes-256-gcm
      -O keyformat=passphrase
      -O keylocation=prompt
      {{ installation_zfs_additional_zpool_properties | default('') | trim }}
      zroot {{ installation_drive.name }}{{ installation_drive.root_partition_suffix }}
    responses:
      (?i)passphrase: "{{ crypt_passphrase }}"
  no_log: false
  changed_when: true

- name: Create datasets
  ansible.builtin.command: zfs create {{ item.properties }} {{ item.name }}
  changed_when: true
  loop: "{{ installation_zfs_datasets }}"

- name: Export zroot
  ansible.builtin.command: zpool export zroot
  changed_when: true

- name: Get zroot id # noqa risky-shell-pipe
  ansible.builtin.shell: zpool import | grep -oP '(?<=id:).*'
  changed_when: false
  register: installation_zfs_zroot_import_id_result

- name: Import zroot
  ansible.builtin.command: zpool import {{ installation_zfs_zroot_import_id_result.stdout | trim }} -R /mnt zroot
  changed_when: true

- name: Open zroot
  ansible.builtin.expect:
    command: zfs load-key zroot
    responses:
      (?i)passphrase: "{{ crypt_passphrase }}"

- name: Mount datasets and configure properties and cache
  ansible.builtin.command: "{{ item }}"
  changed_when: true
  loop:
    - "zfs mount {{ installation_zfs_root_dataset }}"
    - "zfs mount -a"
    - "zpool set bootfs={{ installation_zfs_root_dataset }} zroot"
    - "zpool set cachefile=/etc/zfs/zpool.cache zroot"
    - "mkdir -p /mnt/etc/zfs"
    - "cp /etc/zfs/zpool.cache /mnt/etc/zfs/zpool.cache"

- name: Create mountpoints for efi
  ansible.builtin.file:
    path: /mnt{{ installation_efi_partiton_mount_point }}
    state: directory
    mode: "0700"

- name: Mount EFI filesystem
  ansible.posix.mount:
    path: /mnt{{ installation_efi_partiton_mount_point }}
    src: "{{ installation_drive.name }}{{ installation_drive.efi_partition_suffix }}"
    fstype: vfat
    passno: 2
    state: mounted

- name: Bind mount boot when uki disabled
  ansible.posix.mount:
    path: /mnt/boot
    src: /mnt/{{ installation_efi_partiton_mount_point }}
    fstype: btrfs
    opts: bind,defaults
    state: mounted
  when: not installation_uki_enabled
