---

- name: Copy blank fstab
  ansible.builtin.template:
    src: fstab.j2
    dest: /mnt/etc/fstab
    owner: root
    group: root
    mode: "0644"
  changed_when: true

- name: Add subvolumes to fstab
  ansible.posix.mount:
    fstab: /mnt/etc/fstab
    path: "{{ item.mount_point }}"
    src: UUID={{ installation_cryptroot_uuid.stdout }}
    fstype: btrfs
    opts: subvol={{ item.name }},compress=zstd:1
    passno: "0"
    state: present
  loop: "{{ installation_btrfs_subvolumes }}"

- name: Add EFI volume to fstab
  ansible.posix.mount:
    fstab: /mnt/etc/fstab
    path: /efi
    src: UUID={{ installation_efi_uuid.stdout }}
    fstype: vfat
    opts: defaults
    passno: "2"
    state: present

- name: Set label for boot partition
  ansible.builtin.command: >
    arch-chroot /mnt fatlabel
    {{ installation_drive.name }}{{ installation_drive.efi_partition_suffix }} "{{ installation_drive.efi_partition_label }}"
  changed_when: true

- name: Set label for root partition
  ansible.builtin.command: >
    arch-chroot /mnt cryptsetup config
    --label="{{ installation_drive.root_partition_label }}_crypt" {{ installation_drive.name }}{{ installation_drive.root_partition_suffix }}
  changed_when: true
