---

- name: Copy blank fstab
  ansible.builtin.template:
    src: fstab.j2
    dest: /mnt/etc/fstab
    owner: root
    group: root
    mode: "0644"
  changed_when: true

- name: Add EFI volume to fstab
  ansible.posix.mount:
    fstab: /mnt/etc/fstab
    path: "{{ installation_efi_partiton_mount_point }}"
    src: UUID={{ installation_efi_uuid.stdout }}
    fstype: vfat
    opts: defaults
    passno: "2"
    state: present

- name: Bind mount boot when uki disabled
  ansible.posix.mount:
    fstab: /mnt/etc/fstab
    path: /boot
    src: "{{ installation_efi_partiton_mount_point }}"
    fstype: zfs
    opts: bind,defaults
    state: present
  when: not installation_uki_enabled

- name: Set label for boot partition
  ansible.builtin.command: >
    arch-chroot /mnt fatlabel
    {{ installation_drive.name }}{{ installation_drive.efi_partition_suffix }} "{{ installation_drive.efi_partition_label }}"
  changed_when: true
