---

- name: Ensure local mirror is enabled for repos
  community.general.ini_file:
    path: /etc/pacman.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    modify_inactive_option: false
    mode: "0644"
  loop:
    - { section: "core", option: "Server", value: "{{ pacman_local_mirror_url }}" }
    - { section: "extra", option: "Server", value: "{{ pacman_local_mirror_url }}" }
  when: pacman_local_mirror_enabled | default(false)

- name: Ensure arch.drik.it repo is added
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    insertafter: EOF
    block: |
      [aur]
      SigLevel = Optional TrustAll
      Server = https://arch.drik.it

- name: Update cache
  community.general.pacman:
    update_cache: true

- name: Run pacstrap to install base system
  ansible.builtin.command: >
    pacstrap /mnt base bind inetutils base-devel linux linux-headers linux-firmware zfs-dkms zfs-utils
    vim nano sudo htop networkmanager e2fsprogs dosfstools ntfs-3g intel-ucode git openssh rsync mkinitcpio-firmware
    python python-pexpect python-lxml sudo sbctl tpm2-tools efibootmgr less {{ installation_additional_packages }}
  changed_when: true

- name: Make sure pacman hook dir exisits
  ansible.builtin.file:
    path: /mnt/etc/pacman.d/hooks
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Set hostname
  ansible.builtin.copy:
    content: "{{ hostname }}"
    dest: /mnt/etc/hostname
    owner: root
    group: root
    mode: "0644"

- name: Set hosts
  ansible.builtin.copy:
    content: |
      127.0.0.1   localhost
      ::1         localhost
      127.0.1.1   {{ hostname }}.{{ localdomain }}  {{ hostname }}
    dest: /mnt/etc/hosts
    owner: root
    group: root
    mode: "0644"
