---

- name: Enable dns service
  ansible.builtin.command: arch-chroot /mnt systemctl enable systemd-resolved
  changed_when: true

- name: Enable network service
  ansible.builtin.command: arch-chroot /mnt systemctl enable NetworkManager
  changed_when: true

- name: Enable network service
  ansible.builtin.command: arch-chroot /mnt systemctl enable sshd
  changed_when: true

- name: Enable qemu-guest-agent service
  ansible.builtin.command: arch-chroot /mnt systemctl enable qemu-guest-agent.service
  changed_when: true
  when: gpu_manufacturer == "virt"
