---

- name: Install systemd-boot
  ansible.builtin.command: arch-chroot /mnt bootctl install
  changed_when: true

- name: Enable systemd-boot update service
  ansible.builtin.command: arch-chroot /mnt systemctl enable systemd-boot-update.service
  changed_when: true

- name: Create pacman hook for updating systemd-boot after systemd update
  ansible.builtin.template:
    src: 95-systemd-boot.hook.j2
    dest: /mnt/etc/pacman.d/hooks/95-systemd-boot.hook
    owner: root
    group: root
    mode: "0644"
