controller:
  replicaCount: {{ nginx_ingress_replicas }}
  resources: {{ nginx_ingress_resources }}
  ingressClassResource:
    name: nginx
    default: true
  dnsConfig:
    options:
      - name: ndots
        value: '1'
  service:
    loadBalancerIP: {{ nginx_ingress_load_balancer_ip }}