---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.*
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 30m
  timeout: 25m
  releaseName: ingress-nginx
  valuesFrom:
  - kind: ConfigMap
    name: ingress-nginx-values
    valuesKey: values.yaml
