---

- name: Add nginx-ingress chart repo
  kubernetes.core.helm_repository:
    repo_name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Deploy Grafana chart using values files on target
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'ingress-nginx-values.yaml') | from_yaml }}"
