---

- name: Ensure packages are updated
  pacman:
    update_cache: true
    upgrade: true

- name: Ensure hardcode-tray and icons are installed
  pacman:
    name:
      - hardcode-tray-git
      - papirus-icon-theme
      - libappindicator-gtk3
    state: present

- name: Make sure drik-dark icon theme is present
  copy:
    src: drik-dark
    dest: /usr/share/icons
    mode: 0755
    owner: root
    group: root
  notify: Update tray
