---

- name: Ensure ufw is installed
  community.general.pacman:
    name:
      - ufw
    state: present

- name: Configure ufw defaults
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify:
    - "ufw : Restart ufw"

- name: Configure ufw ssh rules
  community.general.ufw:
    rule: limit
    port: 22
    proto: tcp
    src: 192.168.0.0/16
  notify:
    - "ufw : Restart ufw"

- name: Configure ufw nfs rules
  community.general.ufw:
    rule: allow
    port: 2049
    proto: tcp
    src: 192.168.0.0/16
  notify:
    - "ufw : Restart ufw"
  when: nfs_enabled | bool

- name: Enable ufw logging
  community.general.ufw:
    logging: true
  notify:
    - "ufw : Restart ufw"

- name: Enable ufw
  community.general.ufw:
    state: enabled

- name: Enable ufw service
  ansible.builtin.systemd:
    name: ufw
    state: started
    enabled: true
