---

- name: Run reflector
  ansible.builtin.systemd:
    name: reflector
    state: started
  become: true

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Update cache
  community.general.pacman:
    update_cache: true
