---

- name: Set local timezone
  ansible.builtin.command: arch-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/Warsaw /etc/localtime
  changed_when: true

- name: Set hardware clock from system clock
  ansible.builtin.command: arch-chroot /mnt hwclock --systohc
  changed_when: true

- name: Configure locale.gen
  ansible.builtin.lineinfile:
    dest: /mnt/etc/locale.gen
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  loop:
    - {regex: en_US\.UTF-8 UTF-8, line: en_US.UTF-8 UTF-8}
    - {regex: en_GB\.UTF-8 UTF-8, line: en_GB.UTF-8 UTF-8}
    - {regex: pl_PL\.UTF-8 UTF-8, line: pl_PL.UTF-8 UTF-8}

- name: Create locale.conf
  ansible.builtin.template:
    src: locale.conf.j2
    dest: /mnt/etc/locale.conf
    owner: root
    group: root
    mode: "0644"

- name: Set keymap
  ansible.builtin.copy:
    content: "KEYMAP=pl"
    dest: /mnt/etc/vconsole.conf
    owner: root
    group: root
    mode: "0644"

- name: Generate locales
  ansible.builtin.command: arch-chroot /mnt locale-gen
  changed_when: true
