---

- name: Abort if the host is not booted from the Arch install media
  ansible.builtin.fail:
    msg: "This host is not booted from the Arch install media!"
  when:
    - ansible_nodename != 'archiso'
    - installation_no_hostname_check | default(true) | bool

- name: Set polish keyboard
  ansible.builtin.command: loadkeys pl
  changed_when: true

- name: Ensure NTP is running
  ansible.builtin.service:
    name: systemd-timesyncd
    state: started
    enabled: true
