---

- name: Install systemd-boot
  ansible.builtin.command: arch-chroot /mnt bootctl install
  changed_when: true

- name: Create loader entry
  ansible.builtin.template:
    src: arch.conf.j2
    dest: /mnt/boot/loader/entries/{{ item }}.conf
    owner: root
    group: root
    mode: "0600"
  loop:
    - arch
    - arch-fallback
  when: not installation_uki_enabled

- name: Enable systemd-boot update service
  ansible.builtin.command: arch-chroot /mnt systemctl enable systemd-boot-update.service
  changed_when: true

- name: Create pacman hook for updating systemd-boot after systemd update
  ansible.builtin.template:
    src: 95-systemd-boot.hook.j2
    dest: /mnt/etc/pacman.d/hooks/95-systemd-boot.hook
    owner: root
    group: root
    mode: "0644"
