---

- name: Create kubectl config dir
  ansible.builtin.file:
    dest: /root/.kube
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Configure kubectl for root
  ansible.builtin.copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: "0600"
    owner: root
    group: root
