---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: bazarr
spec:
  chart:
    spec:
      chart: bazarr
      version: 0.1.*
      sourceRef:
        kind: HelmRepository
        name: drik-homelab
        namespace: flux-system
  interval: 30m
  timeout: 15m
  releaseName: bazarr
  valuesFrom:
  - kind: ConfigMap
    name: bazarr-values
    valuesKey: values.yaml
