---

- name: Ensure steam and other packages are installed
  community.general.pacman:
    name:
      - lib32-mesa
      - steam
      - libstrangle-git
      - lib32-gamemode
      - gamemode
      - proton-ge-custom-bin
      - lib32-gnutls
      - lib32-libldap
      - lib32-libgpg-error
      - lib32-sqlite
      - lib32-libpulse
      - lib32-alsa-plugins
    state: present

- name: Additional packages for nvidia
  community.general.pacman:
    name:
      - lib32-nvidia-utils
    state: present
  when:
    - gpu_manufacturer == "nvidia"

- name: Ensure gamemode group exists
  ansible.builtin.group:
    name: gamemode
    state: present

- name: Add user to gamemode group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: gamemode
    append: true

- name: Add user to games group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: games
    append: true

- name: Make sure gamemode config is correct
  ansible.builtin.copy:
    src: gamemode.ini
    dest: /home/{{ user_name }}/.config/gamemode.ini
    mode: "0644"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
