---

- block:

  - name: Ensure packages are updated
    pacman:
      update_cache: yes
      upgrade: yes

  - name: Ensure spectacle is installed
    pacman:
      name:
        - spectacle
      state: present

  become: yes

- name: Set spectaclerc (spectacle settings)
  template:
    src: spectaclerc.j2
    dest: /home/{{ user_name }}/.config/spectaclerc
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"


- name: Change spectacle shortcuts
  lineinfile:
    dest: /home/{{ user_name }}/.config/kglobalshortcutsrc
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - {regex: "RectangularRegionScreenShot=", line: "RectangularRegionScreenShot=Meta+Shift+S,Meta+Shift+Print,Capture Rectangular Region"}
    - {regex: "WindowUnderCursorScreenShot=", line: "WindowUnderCursorScreenShot=Meta+Ctrl+S,Meta+Ctrl+Print,Capture Window Under Cursor"}

