---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: ingress-nginx-internal
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.*
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 15m
  timeout: 10m
  releaseName: ingress-nginx-internal
  valuesFrom:
  - kind: ConfigMap
    name: ingress-nginx-internal-values
    valuesKey: values.yaml
