---
apiVersion: v1
kind: Service
metadata:
  name: valetudo-service
  namespace: ingress-nginx-internal
spec:
  externalName: u02293zm.off.drik.it
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ExternalName

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx-internal
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
  labels:
    app.kubernetes.io/name: valetudo
  name: valetudo-ingress
  namespace: ingress-nginx-internal
spec:
  ingressClassName: nginx-internal
  rules:
  - host: valetudo.drik.it
    http:
      paths:
      - backend:
          service:
            name: valetudo-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - valetudo.drik.it
    secretName: valetudo-certs
