---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-values
  namespace: authentik
data:
  values.yaml: |-
    server:
      resources: {}
      replicas: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - auth.drik.it
        paths:
          - /
        pathType: Prefix
        tls:
          - hosts:
            - auth.drik.it
            secretName: authentik-certs
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      volumeMounts:
        - name: authentik-cert-vol
          mountPath: /certs/authentik
          readOnly: true
      volumes:
        - name: authentik-cert-vol
          secret:
            secretName: authentik-certs
            items:
              - key: tls.crt
                path: fullchain.pem
              - key: tls.key
                path: privkey.pem
    worker:
      resources: {}
      replicas: 1
      dnsConfig:
        options:
          - name: ndots
            value: '1'

    authentik:
      error_reporting:
          enabled: false
      disable_startup_analytics: true

    postgresql:
      enabled: true
      clusterDomain: cluster.drik.it
      primary:
        resources: {}
      readReplicas:
        resources: {}

    redis:
      enabled: true
      auth:
        enabled: true
      clusterDomain: cluster.drik.it
