---

- name: Ensure packages are upgraded
  community.general.pacman:
    update_cache: true
    upgrade: true
  register: upgrade_result
  notify: Reboot after upgrade

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
