---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      chart: jellyfin
      version: latest
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: jellyfin
  valuesFrom:
  - kind: ConfigMap
    name: jellyfin-values
    valuesKey: values.yaml
