---

- name: Init kube cluster
  ansible.builtin.command: >
    kubeadm init
    --cri-socket=unix:/run/containerd/containerd.sock
    --pod-network-cidr='{{ kubernetes_pod_network }}'
    --control-plane-endpoint='{{ kubernetes_kube_vip_control_plane_address }}'
  changed_when: true

- name: Configure kubectl
  ansible.builtin.import_tasks: kubectl.yml

- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted

- name: Install pod network addon
  ansible.builtin.command: cilium-cli install
  changed_when: true
