---

- name: Get join token
  ansible.builtin.command: kubeadm token create --print-join-command
  register: kubernetes_join_token_result
  changed_when: true
  delegate_to: "{{ hostvars[groups['kube_control'][0]].inventory_hostname }}"

- name: Join node to cluster
  ansible.builtin.command:
    cmd: "{{ kubernetes_join_token_result.stdout + ('--control-plane' if 'kube_control' in group_names else '') }}"
  changed_when: true

- name: Set node role for workers
  ansible.builtin.command: "kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker=worker"
  changed_when: true
  delegate_to: "{{ hostvars[groups['kube_control'][0]].inventory_hostname }}"
  when: "'kube_workers' in group_names"
