---

- name: Get kube-vip version
  ansible.builtin.shell: set -o pipefail && curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name"
  register: kubernetes_kube_vip_version_result
  changed_when: false

- name: Generate manifest
  ansible.builtin.shell: >
    set -o pipefail &&
    ctr image pull ghcr.io/kube-vip/kube-vip:{{ kubernetes_kube_vip_version_result.stdout }};
    ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:{{ kubernetes_kube_vip_version_result.stdout }}
    vip /kube-vip manifest pod
    --interface lo
    --address {{ kubernetes_kube_vip_control_plane_address }}
    --controlplane
    --services
    --bgp
    --localAS {{ kubernetes_kube_vip_local_as }}
    --bgpRouterID {{ kubernetes_kube_vip_router_id }}
    --bgppeers {{ kubernetes_kube_vip_peer_address }}:{{ kubernetes_kube_vip_peer_as }}::false
    | tee /etc/kubernetes/manifests/kube-vip.yaml
  register: kubernetes_kube_vip_version_result
  changed_when: true

- name: Download kube-vip Cloud Provider manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml
    dest: ~/kube-vip-cloud-provider.yaml
    mode: "0664"
    owner: root
    group: root

- name: Apply kube-vip Cloud Provider manifest
  kubernetes.core.k8s:
    state: present
    src: ~/kube-vip-cloud-provider.yaml

- name: Create configmap for kube-vip Cloud Provider
  kubernetes.core.k8s:
    namespace: kube-system
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: kubevip
        namespace: kube-system
      data:
        range-global: "{{ kubernetes_kube_vip_global_range }}"
    apply: true
    server_side_apply:
      field_manager: ansible
