---

- name: Configure ethernet connection with static IP
  community.general.nmcli:
    conn_name: "{{ network_config.connection_name }}"
    ifname: "{{ network_interface }}"
    type: ethernet
    ip4: "{{ network_config.ipv4 }}"
    gw4: "{{ network_config.gw4 }}"
    dns4: "{{ network_config.dns4 | default([]) }}"
    dns4_search: "{{ network_config.dns4_search | default([]) }}"
    state: present
  register: network_config_result
  notify: Reboot after network change
  when: not kvm_enabled

- name: Run kvm configuration
  ansible.builtin.include_role:
    name: kvm
  when: kvm_enabled

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
