---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aurutils
  namespace: aurutils
spec:
  chart:
    spec:
      chart: aurutils
      version: 0.1.*
      sourceRef:
        kind: HelmRepository
        name: drik-homelab
        namespace: flux-system
  interval: 30m
  timeout: 10m
  releaseName: aurutils
  valuesFrom:
  - kind: ConfigMap
    name: aurutils-values
    valuesKey: values.yaml
