---

- name: Ensure bluez is installed
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
    state: present

- name: Enable bluetooth service
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
