---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  chart:
    spec:
      chart: prowlarr
      version: 0.1.*
      sourceRef:
        kind: HelmRepository
        name: drik-homelab
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: prowlarr
  valuesFrom:
  - kind: ConfigMap
    name: prowlarr-values
    valuesKey: values.yaml
