---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.6.*
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
  interval: 15m
  timeout: 10m
  releaseName: csi-driver-nfs
  valuesFrom:
  - kind: ConfigMap
    name: csi-driver-nfs-values
    valuesKey: values.yaml
