---
apiVersion: v1
kind: ConfigMap
metadata:
  name: subgen-values
  namespace: subgen
data:
  values.yaml: |-
    replicaCount: 1
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 30Gi
