---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: subgen
  namespace: bazarr
spec:
  chart:
    spec:
      chart: subgen
      version: 0.1.*
      sourceRef:
        kind: HelmRepository
        name: drik-homelab
        namespace: flux-system
  interval: 45m
  timeout: 30m
  releaseName: subgen
  valuesFrom:
  - kind: ConfigMap
    name: subgen-values
    valuesKey: values.yaml
