---

- name: Post installation configration
  hosts: managed
  become: true
  tasks:

    - name: Basic configuration
      tags: [basic]
      block:
        - name: Network configuration
          ansible.builtin.import_role:
            name: network
          tags: [network]
          when: network_config is defined and network_configure | default(false) | bool

        - name: Package upgrade
          ansible.builtin.import_role:
            name: upgrade
          tags: [upgrade]
          when: package_upgrade | default(false) | bool

        - name: Standard configuration
          ansible.builtin.import_role:
            name: standard
          tags: [standard]

        - name: NTP configuration
          ansible.builtin.import_role:
            name: ntp
          tags: [ntp]

        - name: Pacman configuration
          ansible.builtin.import_role:
            name: pacman
          tags: [pacman]

        - name: Firewall configuration
          ansible.builtin.import_role:
            name: ufw
          when: ufw_enabled | bool
          tags: [ufw]

        - name: KVM configuration
          ansible.builtin.import_role:
            name: kvm
          when: kvm_enabled | bool
          tags: [kvm]

        - name: ZFS configuration
          ansible.builtin.import_role:
            name: zfs
          when: zfs_additional_drives_enabled | bool and zfs_configure | default(false) | bool
          tags: [zfs]

        - name: NFS configuration
          ansible.builtin.import_role:
            name: nfs
          when: nfs_enabled | bool and nfs_configure | default(false) | bool
          tags: [nfs]

        - name: Sanoid configuration
          ansible.builtin.import_role:
            name: sanoid
          when: sanoid_enabled | bool
          tags: [sanoid]

    - name: GUI configuration
      when: gui_enabled | bool
      block:
        - name: Plasma configuration
          ansible.builtin.import_role:
            name: plasma
          tags: [plasma]

        - name: SDDM configuration
          ansible.builtin.import_role:
            name: sddm
          tags: [sddm]

        - name: KDEconnect configuration
          ansible.builtin.import_role:
            name: kdeconnect
          tags: [kdeconnect]

        - name: Bluetooth configuration
          ansible.builtin.import_role:
            name: bluetooth
          tags: [bluetooth]

        - name: Print configuration
          ansible.builtin.import_role:
            name: print
          tags: [print]

        - name: Standard apps configuration
          ansible.builtin.import_role:
            name: standard_apps
          tags: [standard_apps]

        - name: Personal apps configuration
          when: host_type == "personal"
          ansible.builtin.import_role:
            name: personal_apps
          tags: [personal_apps]

    - name: GUI personalization
      when: gui_enabled | bool
      block:
        - name: System settings configuration
          ansible.builtin.import_role:
            name: system_settings
          tags: [system_settings]

        - name: Dolphin configuration
          ansible.builtin.import_role:
            name: dolphin
          tags: [dolphin]

        - name: Kate configuration
          ansible.builtin.import_role:
            name: kate
          tags: [kate]

        - name: Konsole configuration
          ansible.builtin.import_role:
            name: konsole
          tags: [konsole]

        - name: Okular configuration
          ansible.builtin.import_role:
            name: okular
          tags: [okular]

        - name: Gwenview configuration
          ansible.builtin.import_role:
            name: gwenview
          tags: [gwenview]

        - name: Spectacle configuration
          ansible.builtin.import_role:
            name: spectacle
          tags: [spectacle]

        - name: KDEwallet configuration
          ansible.builtin.import_role:
            name: kdewallet
          when:
            - kwl is file
            - salt is file
          tags: [kdewallet]

        - name: Librewolf configuration
          ansible.builtin.import_role:
            name: librewolf
          tags: [librewolf]

        - name: VPN GUI configuration
          ansible.builtin.import_role:
            name: vpn_gui
          tags: [vpn_gui]

        - name: Remmina configuration
          when: host_type == "personal"
          ansible.builtin.import_role:
            name: remmina
          tags: [remmina]

        - name: Signal configuration
          ansible.builtin.import_role:
            name: signal
          tags: [signal]

        - name: Steam configuration
          when: host_type == "personal"
          ansible.builtin.import_role:
            name: steam
          tags: [steam]

        - name: Hardcode_tray configuration
          ansible.builtin.import_role:
            name: hardcode_tray
          tags: [hardcode_tray]

        - name: Clear plasma cache
          ansible.builtin.import_role:
            name: clear_cache
          tags: [clear_cache]

    - name: Kubernetes installation
      when: kubernetes_enabled | bool
      tags: [kubernetes, kubernetes_install]
      block:
        - name: Install and configure kubernetes
          ansible.builtin.import_role:
            name: kubernetes
          tags: [kubernetes_kubeadm]

        - name: Install and configure onepassword
          ansible.builtin.import_role:
            name: onepassword
          tags: [onepassword]

    - name: Kubernetes configuration
      when: kubernetes_enabled | bool and kubernetes_control_plane_node | bool
      tags: [kubernetes, kubernetes_config]
      block:
        - name: Install and configure nginx-ingress
          ansible.builtin.import_role:
            name: nginx_ingress
          tags: [nginx_ingress, ingress_nginx]

        - name: Install and configure cert-manager
          ansible.builtin.import_role:
            name: cert_manager
          tags: [cert_manager]

        - name: Install and configure cilium
          ansible.builtin.import_role:
            name: cilium
          tags: [cilium]

        - name: Install and configure csi-driver-nfs
          ansible.builtin.import_role:
            name: csi_driver_nfs
          tags: [csi_driver_nfs]

        - name: Install and configure zfs-localpv
          ansible.builtin.import_role:
            name: zfs_localpv
          tags: [zfs_localpv]

        - name: Install and configure authentik
          ansible.builtin.import_role:
            name: authentik
          tags: [authentik]

        - name: Install and configure metrics-server
          ansible.builtin.import_role:
            name: metrics_server
          tags: [metrics_server]

        - name: Install and configure kubernetes-dashboard
          ansible.builtin.import_role:
            name: kubernetes_dashboard
          tags: [kubernetes_dashboard]

        - name: Install and configure dagonite-empire
          ansible.builtin.import_role:
            name: dagonite_empire
          tags: [dagonite_empire]

        - name: Install and configure jellyfin
          ansible.builtin.import_role:
            name: jellyfin
          tags: [jellyfin]
