---

installation_drive:
  name: /dev/disk/by-id/virtio-vda
  efi_partition_suffix: -part1
  efi_partition_label: efi
  root_partition_suffix: -part2
  root_zpool: arch

hostname: kube-2
gpu_manufacturer: virt
# en_PL, pl_PL
system_language: en_PL

network_config:
  connection_name: "Wired connection 1"
  ipv4: 192.168.100.82/24
  gw4: 192.168.100.1
  dns4: 192.168.100.1
  dns4_search: "{{ localdomain }}"
