---

- name: Set kded5rc
  ansible.builtin.copy:
    src: kded5rc
    dest: /home/{{ user_name }}/.config/kded5rc
    mode: "0600"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  when: 'system_settings_replace_result.msg is defined'
