---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-values
  namespace: vaultwarden
data:
  values.yaml: |-
    resources: {}
    data:
      name: "vaultwarden-data"
      size: "50Gi"
      path: "/data"
    database:
      type: "postgresql"
      host: "vaultwarden-postgresql"
    pushNotifications:
      relayUri: "https://push.bitwarden.eu"
      identityUri: "https://identity.bitwarden.eu"
    domain: "vault.drik.it"
    sendsAllowed: "true"
    signupsAllowed: false"
    invitationsAllowed: true
    invitationOrgName: "Vault | Drik.IT"
    adminToken: null
    ingress:
      enabled: true
      class: "nginx"
      nginxIngressAnnotations: true
      additionalAnnotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: true
      hostname: "vault.drik.it"
      tlsSecret: "vaultwarden-tls"
    postgresql:
      clusterDomain: cluster.drik.it
