---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  chart:
    spec:
      chart: vaultwarden
      version: 0.22.*
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: vaultwarden
  valuesFrom:
  - kind: ConfigMap
    name: vaultwarden-values
    valuesKey: values.yaml
  - kind: Secret
    name: vaultwarden-secret-values
    valuesKey: notesPlain
