---

- name: Add jetstack chart repo
  kubernetes.core.helm_repository:
    repo_name: jetstack
    repo_url: https://charts.jetstack.io

- name: Deploy cert-manager chart
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'cert-manager-values.yaml') | from_yaml }}"
