---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: jellyseerr
spec:
  chart:
    spec:
      chart: jellyseerr
      version: 0.1.*
      sourceRef:
        kind: HelmRepository
        name: drik-homelab
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: jellyseerr
  valuesFrom:
  - kind: ConfigMap
    name: jellyseerr-values
    valuesKey: values.yaml
