---

- name: Make sure config dir exisits
  ansible.builtin.file:
    path: /home/{{ user_name }}/.config
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"

- name: Copy local.conf fonts config file
  ansible.builtin.copy:
    src: fonts-local.conf
    dest: /etc/fonts/local.conf
    owner: root
    group: root
    mode: "0755"
  notify:
    - Fc cache

- name: Copy local.conf fonts config file
  ansible.builtin.copy:
    src: Xresources
    dest: /home/{{ user_name }}/.Xresources
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0644"
  notify:
    - Fc cache

- name: Create symbolic link for fonts part 1
  ansible.builtin.file:
    src: /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf
    dest: /etc/fonts/conf.d/10-sub-pixel-rgb.conf
    state: link
    owner: root
    group: root
    mode: "0644"
  notify:
    - Fc cache

- name: Create symbolic link for fonts part 2
  ansible.builtin.file:
    src: /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf
    dest: /etc/fonts/conf.d/11-lcdfilter-default.conf
    state: link
    owner: root
    group: root
    mode: "0644"
  notify:
    - Fc cache

- name: Make sure fontconfig dir exisits
  ansible.builtin.file:
    path: /home/{{ user_name }}/.config/fontconfig
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"

- name: Copy fonts.conf fonts config file
  ansible.builtin.copy:
    src: fonts.conf
    dest: /home/{{ user_name }}/.config/fontconfig/fonts.conf
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0644"
  notify:
    - Fc cache
